[project]
name = "ai_workflow_and_agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "groq>=0.16.0",
    "ipykernel>=6.29.5",
]
