[project]
name = "ai_workflow_and_agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopy>=2.4.1",
    "groq>=0.16.0",
    "jupyterlab>=4.3.5",
    "python-dotenv>=1.0.1",
]
